### ISSUE TITLE
Relation to cargo-script 

### ISSUE THREAD

**Issue by theduke** [fanzeyi/cargo-play#1] opened 2019-05-27 04:38 UTC
This seems to be an almost-duplicate of https://github.com/DanielKeep/cargo-script, or am I missing something?

**Comment by fanzeyi** [comment] 2019-06-21 06:26
No, this is not a duplicate of [cargo-script](https://github.com/DanielKeep/cargo-script). I admit both project do something very similar but with fundamentally different intentions. My understanding is that cargo-script focuses on letting people run Rust programs while cargo-play is focusing on helping people *experimenting* Rust code. In other words, these two projects are going towards different directions from a very close starting point.

Hope this answered your question. Closing this now.

**Closed by fanzeyi** 2019-06-21 06:26 UTC

**Comment by theduke** [comment] 2019-06-21 09:31
I wasn't implying that this project is in any way misguided btw, since `cargo-script` seems unmaintained/abandoned, and I enjoy the functionality very much (eg for writing one-off scripts like deployment/build setup stuff).
